### ISSUE TITLE
The project can't be built by Keil MDK-ARM.

### ISSUE THREAD

**Issue by hatahuang1214** [Infineon/optiga-trust-charge#1]
Hi, Sir,
Please help to check that the project can't be built by Keil MDK-ARM.
I put the error logs as the attached.. Please let me know what things I need to modify or change... Thanks in advance
[Build_Output.txt](https://github.com/Infineon/optiga-trust-charge/files/6506855/Build_Output.txt)

**Comment by ayushev** [comment]
Hello @hatahuang1214 

The version of the Keil we used is 5.25.2.0, the DFP is 2.11.0. It might be that the second error you have is comming from the DFP version, can you please select the one we used?

In regards to the mbedtls error, please substitute this file https://github.com/Infineon/optiga-trust-charge/blob/master/externals/mbedtls/include/mbedtls/config.h with that https://github.com/Infineon/optiga-trust-charge/blob/46069a618780bb27a86cb65c726e2d81d8372d15/externals/mbedtls/include/mbedtls/config.h

**Comment by 674544116** [comment]
Hi,Sir
    I made a mistake when compiling with Keil. Could you please help to check it?

****************************************************************************************************
*** Using Compiler 'V5.06 update 4 (build 422)', folder: 'D:\Software\Keil5\ARM\ARMCC\Bin'
Build target 'XMC4700-F144x2048'
compiling pal_crypt_mbedtls.c...
..\..\..\externals\mbedtls\include\mbedtls/ssl.h(414): error:  #169: expected a declaration
  };
..\..\..\pal\pal_crypt_mbedtls.c: 0 warnings, 1 error
".\UVBuild\xmc4700_optiga_example.axf" - 1 Error(s), 0 Warning(s).
Target not created.
Build Time Elapsed:  00:00:10

**Comment by ayushev** [comment]
Hello @674544116 
could you please attach the full output here?
Also please mention which verson of the Keil and DFP you are using (assuming the compiler is V5.06).

**Comment by 674544116** [comment]
Hello&nbsp;ayushev
&nbsp; &nbsp;The Keil version is 5.23, and the DFP version is 2.11.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Infineon/optiga-trust-charge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Infineon/optiga-trust-charge] The project can't be built by Keil MDK-ARM. (#1)





 
Hello @674544116
 could you please attach the full output here?
 Also please mention which verson of the Keil and DFP you are using (assuming the compiler is V5.06).

**Comment by ayushev** [comment]
can you please paste here the full build output, to see what exactly happens? A similar output what the author of this topic has attached.

**Comment by 674544116** [comment]
> can you please paste here the full build output, to see what exactly happens? A similar output what the author of this topic has attached.

**Here is the total output：**

*** Using Compiler 'V5.06 update 4 (build 422)', folder: 'D:\Software\Keil5\ARM\ARMCC\Bin'
Build target 'XMC4700-F144x2048'
compiling pal_crypt_mbedtls.c...
..\..\..\externals\mbedtls\include\mbedtls/ssl.h(414): error:  #169: expected a declaration
  };
..\..\..\pal\pal_crypt_mbedtls.c: 0 warnings, 1 error
".\UVBuild\xmc4700_optiga_example.axf" - 1 Error(s), 0 Warning(s).
Target not created.
Build Time Elapsed:  00:00:10

**Comment by ayushev** [comment]
Did you try to follow my advice regarding the mbedtls/config.h I gave above?

**Comment by 674544116** [comment]
> Did you try to follow my advice regarding the mbedtls/config.h I gave above?

I've just tried it. It OK, thank you very much.
